basePath: /
definitions:
  models.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  models.OrderItem:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      orderID:
        description: Bağlı olduğu sipariş
        type: integer
      price:
        description: Birim fiyat
        type: number
      productID:
        description: Ürün kimliği
        type: integer
      quantity:
        description: Miktar
        type: integer
      total:
        description: Toplam fiyat
        type: number
      updatedAt:
        type: string
    type: object
  models.PasswordUpdateRequest:
    properties:
      new_password:
        example: new_password123
        type: string
      old_password:
        example: old_password123
        type: string
    type: object
  models.Product:
    type: object
  models.Shop:
    type: object
  models.User:
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an e-commerce server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: E-Commerce API
  version: "1.0"
paths:
  /myshop/products:
    get:
      description: Get the details of all products for the logged-in user's shop
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "404":
          description: Shop or products not found
          schema:
            type: string
      summary: Get products by the logged-in user's shop
      tags:
      - Products
  /orders/{product_id}:
    post:
      consumes:
      - application/json
      description: Create a new order for a product with the specified quantity
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      - description: Order Item
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.OrderItem'
      produces:
      - application/json
      responses:
        "200":
          description: Order created successfully
          schema:
            type: string
        "400":
          description: Invalid id" / "Invalid input" / "Not available in the required
            quantity
          schema:
            type: string
        "404":
          description: Product not found
          schema:
            type: string
        "500":
          description: Failed to create order" / "Failed to create order item" / "Failed
            to begin transaction" / "Failed to commit transaction
          schema:
            type: string
      summary: Create a new order
      tags:
      - Orders
  /products:
    get:
      description: Get the details of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "404":
          description: Products not found
          schema:
            type: string
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Add a new product to the shop of the logged-in user
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Shop not found
          schema:
            type: string
        "500":
          description: Failed to create product
          schema:
            type: string
      summary: Add a new product
      tags:
      - Products
  /products/{product_id}:
    get:
      description: Get the details of a product by its ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Invalid id
          schema:
            type: string
        "404":
          description: Product not found
          schema:
            type: string
      summary: Get a product by ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update the details of an existing product
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      - description: Updated product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated successfully.
          schema:
            type: string
        "400":
          description: Invalid id or input
          schema:
            type: string
        "404":
          description: Product not found
          schema:
            type: string
        "500":
          description: Failed to update product
          schema:
            type: string
      summary: Update an existing product
      tags:
      - Products
  /shops:
    post:
      consumes:
      - application/json
      description: Create a new shop for the logged-in seller
      parameters:
      - description: Shop
        in: body
        name: shop
        required: true
        schema:
          $ref: '#/definitions/models.Shop'
      produces:
      - application/json
      responses:
        "201":
          description: Shop created successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Failed to create shop
          schema:
            type: string
      summary: Create a new shop
      tags:
      - Shop
    put:
      consumes:
      - application/json
      description: Update the information of the logged-in user's shop
      parameters:
      - description: Shop
        in: body
        name: shop
        required: true
        schema:
          $ref: '#/definitions/models.Shop'
      produces:
      - application/json
      responses:
        "200":
          description: Shop updated successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Shop not found
          schema:
            type: string
        "500":
          description: Failed to update shop
          schema:
            type: string
      summary: Update shop information
      tags:
      - Shop
  /shops/{shop_id}:
    get:
      description: Get information of a shop by shop ID
      parameters:
      - description: Shop ID
        in: path
        name: shop_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Shop'
        "400":
          description: Invalid shop id
          schema:
            type: string
        "404":
          description: Shop not found
          schema:
            type: string
      summary: Get shop information
      tags:
      - Shop
  /shops/my:
    get:
      description: Get information of the logged-in user's shop
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Shop'
        "404":
          description: Shop not found
          schema:
            type: string
        "500":
          description: Failed to retrieve shop
          schema:
            type: string
      summary: Get my shop information
      tags:
      - Shop
  /users/{id}:
    delete:
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: User deleted successfully
          schema:
            type: string
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
      summary: Delete a user
      tags:
      - User
  /users/close-account:
    delete:
      description: Close the account of the logged-in user
      responses:
        "204":
          description: Account closed successfully
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Failed to close account
          schema:
            type: string
      summary: Close user account
      tags:
      - User
  /users/login:
    post:
      consumes:
      - application/json
      description: Login a user with email and password
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Logged in successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "401":
          description: Invalid email or password
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Login a user
      tags:
      - User
  /users/profile:
    get:
      description: Get the profile of the logged-in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
      summary: Get user profile
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update the profile of the logged-in user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: Profile updated successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update user profile
      tags:
      - User
  /users/profile/password:
    put:
      consumes:
      - application/json
      description: Update the password of the logged-in user
      parameters:
      - description: Password Update Request
        in: body
        name: passwordData
        required: true
        schema:
          $ref: '#/definitions/models.PasswordUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password updated successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update user password
      tags:
      - User
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user with username, password, email, and role
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Register a new user
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
